// Bundled fallback data for standalone `vite dev` / `preview` with no backend.
// Hand-authored from the mock's sessions-data.js schema — a handful of
// representative runs across every channel, incl. one silent (NOTHING_TO_REPORT)
// and one live "running" run. This lets the whole UI be developed offline.

import type { Session, WebInstance } from "./types";

export const FIXTURE_INSTANCES: WebInstance[] = [
  {
    sourceId: "personal-agent",
    label: "personal-agent",
    cwd: "/Users/example/personal-agent",
    artifactDir: "/Users/example/personal-agent/.mono-agent/runs",
    health: "ok",
    liveConnected: true,
    counts: { runs: 4 },
  },
  {
    sourceId: "orchestrator",
    label: "orchestrator",
    cwd: "/Users/example/a8c-agents/orchestrator",
    artifactDir: "/Users/example/a8c-agents/orchestrator/.mono-agent/runs",
    health: "ok",
    liveConnected: true,
    counts: { runs: 2 },
  },
];

export const FIXTURE_SESSIONS: Session[] = [
  // 1 — CRON focus-scan, silent (NOTHING_TO_REPORT). The archetype run.
  {
    id: "2582cf1d-636e-475c-ac72-eab20e09d829",
    cwd: "/Users/example/personal-agent",
    instance: "personal-agent",
    sourceId: "personal-agent",
    startTs: "2026-07-04T07:10:00.153Z",
    durMs: 428230,
    kind: "focus-scan",
    trigger: "cron",
    source: "cron",
    title: "Hourly focus scan",
    outcome: "silent",
    model: "gpt-5.5",
    provider: "openai-codex",
    api: "openai-codex-responses",
    effort: "medium",
    instr:
      "Run the hourly focus scan. Follow the `focus-scan` skill for the bounded delta-first workflow across Robert and Paola Gmail/Calendar, the A8C Maven-only Gmail check, WhatsApp, the Drafts inbox and the `inbox/` drop-zone, Todoist capture, KB filing, the dashboard regen, memory, and the notification.\n\nAfter capture/KB updates are attempted, your **final answer is the delta card** per `telegram-notifications` (native notify — delivered verbatim) when there is a new/changed item worth interrupting Robert; otherwise reply exactly `NOTHING_TO_REPORT`.",
    instrTr: false,
    recalled:
      "## Memory (recalled)\n\n- After capture and KB updates, return a delta card only for a new/changed item needing interruption; otherwise reply exactly NOTHING_TO_REPORT.\n- Scan Robert and Paola Gmail/Calendar, A8C Maven-only Gmail, WhatsApp, Drafts inbox, `inbox/` drop-zone, Todoist capture, KB, dashboard regen, memory, and notifications.\n- Quiet hours are 22:00–07:00 Europe/Rome; suppress non-urgent notifications in that window.",
    recalledTr: false,
    hasRecall: true,
    finalText: "NOTHING_TO_REPORT",
    finalTr: false,
    status: "done",
    totals: {
      asst: 3,
      tcalls: 3,
      think: 2,
      tokIn: 59489,
      tokOut: 9851,
      tokCache: 797184,
      cost: 0.6415,
      steps: 8,
    },
    toolCounts: { read_skill: 1, Bash: 1, Grep: 1 },
    steps: [
      {
        k: "prompt",
        ts: "2026-07-04T07:10:00.379Z",
        text: "Run the hourly focus scan. Follow the `focus-scan` skill for the bounded delta-first workflow.",
        tr: false,
      },
      {
        k: "assistant",
        ts: "2026-07-04T07:10:11.141Z",
        think: [
          {
            t: "**Running a focus scan.** I'll read the `focus-scan` skill first, then sweep the mailboxes and Drafts inbox in a bounded pass. Memory recall is already attached, so I can go straight to the skill.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_readskill_1",
            name: "read_skill",
            dig: "focus-scan",
            raw: '{\n  "name": "focus-scan"\n}',
            ok: true,
          },
          {
            id: "call_bash_1",
            name: "Bash",
            dig: "gmail delta --since 1h --label maven",
            raw: '{\n  "command": "gmail delta --since 1h --label maven"\n}',
            ok: true,
          },
        ],
        text: "",
        u: { i: 7148, o: 258, c: 0, cost: 0.3348 },
      },
      {
        k: "result",
        ts: "2026-07-04T07:10:14.221Z",
        tcid: "call_readskill_1",
        tool: "read_skill",
        ok: true,
        dig: "Configured skills root: /Users/example/personal-agent/skills",
        text: "Skill directory: /Users/example/personal-agent/skills/focus-scan\nPath rule: files referenced by SKILL.md are bundled with the skill.",
      },
      {
        k: "result",
        ts: "2026-07-04T07:10:22.882Z",
        tcid: "call_bash_1",
        tool: "Bash",
        ok: true,
        dig: "0 new messages in the last hour",
        text: "maven: 0 new · robert: 0 new · paola: 0 new\nNo delta in the trailing 1h window.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T07:12:40.512Z",
        think: [
          {
            t: "Mailboxes are clean. Let me confirm the Drafts inbox and `inbox/` drop-zone are empty before I settle on staying silent.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_grep_1",
            name: "Grep",
            dig: "TODO|URGENT in inbox/",
            raw: '{\n  "pattern": "TODO|URGENT",\n  "path": "inbox/"\n}',
            ok: true,
          },
        ],
        text: "",
        u: { i: 15194, o: 412, c: 660608, cost: 0.2617 },
      },
      {
        k: "result",
        ts: "2026-07-04T07:12:44.101Z",
        tcid: "call_grep_1",
        tool: "Grep",
        ok: true,
        dig: "No matches",
        text: "No matches found in inbox/.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T07:17:08.383Z",
        think: [],
        calls: [],
        text: "NOTHING_TO_REPORT",
        u: { i: 2272, o: 205, c: 136576, cost: 0.045 },
      },
    ],
  },

  // 2 — WEBHOOK, notified. Deploy webhook that summarised a CI failure.
  {
    id: "d1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6",
    cwd: "/Users/example/a8c-agents/orchestrator",
    instance: "orchestrator",
    sourceId: "orchestrator",
    startTs: "2026-07-04T09:42:11.020Z",
    durMs: 73400,
    kind: "proactive",
    trigger: "webhook",
    source: "webhook",
    title: "CI failure on main — jetpack build",
    outcome: "notified",
    model: "claude-opus-4-8",
    provider: "anthropic",
    api: "anthropic-messages",
    effort: "high",
    instr:
      "A GitHub webhook fired: the `build` job failed on `main`. Investigate the failing step, decide whether it is a flake or a real regression, and if actionable, notify Robert with a one-paragraph summary and the fix direction.",
    instrTr: false,
    hasRecall: false,
    finalText:
      "**Build broke on `main` — real regression, not a flake.**\n\nThe `jetpack build` job failed at the *typecheck* step: `packages/session-web/src/index.ts` exports a type that no longer exists after the observability rename (`RunSummary.failoverHistory`).\n\n- Root cause: PR #84 renamed the field but the re-export wasn't updated.\n- Fix: update the `export type` line and re-run `pnpm -r typecheck`.\n- Blast radius: build-only; nothing shipped.\n\nWant me to open the one-line fix PR?",
    finalTr: false,
    status: "done",
    totals: {
      asst: 2,
      tcalls: 3,
      think: 2,
      tokIn: 38210,
      tokOut: 4120,
      tokCache: 122880,
      cost: 0.412,
      steps: 6,
    },
    toolCounts: { Bash: 2, Read: 1 },
    steps: [
      {
        k: "prompt",
        ts: "2026-07-04T09:42:11.220Z",
        text: "A GitHub webhook fired: the `build` job failed on `main`. Investigate and, if actionable, notify Robert.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T09:42:24.900Z",
        think: [
          {
            t: "I'll pull the failing job's log tail first to see which step broke, then read the offending file. A typecheck failure right after a rename is almost always a stale re-export.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_gh_1",
            name: "Bash",
            dig: "gh run view --log-failed",
            raw: '{\n  "command": "gh run view 998321 --log-failed | tail -40"\n}',
            ok: true,
          },
          {
            id: "call_read_1",
            name: "Read",
            dig: "packages/session-web/src/index.ts",
            raw: '{\n  "file_path": "packages/session-web/src/index.ts"\n}',
            ok: true,
          },
        ],
        text: "",
        u: { i: 21100, o: 1980, c: 0, cost: 0.263 },
      },
      {
        k: "result",
        ts: "2026-07-04T09:42:31.410Z",
        tcid: "call_gh_1",
        tool: "Bash",
        ok: false,
        dig: "TS2305: Module has no exported member 'failoverHistory'",
        text: "src/index.ts(3,10): error TS2305: Module '\"@mono-agent/observability\"' has no exported member 'failoverHistory'.\nError: Process completed with exit code 2.",
      },
      {
        k: "result",
        ts: "2026-07-04T09:42:33.980Z",
        tcid: "call_read_1",
        tool: "Read",
        ok: true,
        dig: "re-exports RunSummary.failoverHistory (stale)",
        text: "export type { RunSummary, failoverHistory } from \"@mono-agent/observability\";",
      },
      {
        k: "assistant",
        ts: "2026-07-04T09:43:19.640Z",
        think: [
          {
            t: "Confirmed: it's a stale re-export from the PR #84 rename, not a flake. I'll write the delta card for Robert with the root cause and the one-line fix.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_gh_2",
            name: "Bash",
            dig: "git log --oneline -1 -- src/index.ts",
            raw: '{\n  "command": "git log --oneline -1 -- packages/session-web/src/index.ts"\n}',
            ok: true,
          },
        ],
        text: "**Build broke on `main` — real regression, not a flake.** The typecheck step fails on a stale re-export after the PR #84 observability rename.",
        u: { i: 17110, o: 2140, c: 122880, cost: 0.149 },
      },
      {
        k: "result",
        ts: "2026-07-04T09:43:22.110Z",
        tcid: "call_gh_2",
        tool: "Bash",
        ok: true,
        dig: "af409eb TUI polish (#117)",
        text: "af409eb TUI polish: agent effort visibility (#117)",
      },
    ],
  },

  // 3 — CHAT, notified (chat runs show no outcome badge in the mock).
  {
    id: "b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2",
    cwd: "/Users/example/personal-agent",
    instance: "personal-agent",
    sourceId: "personal-agent",
    startTs: "2026-07-04T11:05:44.700Z",
    durMs: 21980,
    kind: "chat",
    trigger: "chat",
    source: "chat",
    title: "What's on my calendar tomorrow afternoon?",
    outcome: "notified",
    model: "gpt-5.5",
    provider: "openai-codex",
    api: "openai-codex-responses",
    effort: "low",
    instr: "What's on my calendar tomorrow afternoon?",
    instrTr: false,
    hasRecall: false,
    finalText:
      "Tomorrow afternoon (Europe/Rome) you have:\n\n- **14:00** — 1:1 with Paola (30m)\n- **16:30** — Dentist, Via Roma\n\nThe 15:00–16:00 slot is free if you want to hold focus time.",
    finalTr: false,
    status: "done",
    totals: {
      asst: 1,
      tcalls: 1,
      think: 0,
      tokIn: 4210,
      tokOut: 320,
      tokCache: 0,
      cost: 0.028,
      steps: 3,
    },
    toolCounts: { Bash: 1 },
    steps: [
      {
        k: "prompt",
        ts: "2026-07-04T11:05:44.900Z",
        text: "What's on my calendar tomorrow afternoon?",
      },
      {
        k: "assistant",
        ts: "2026-07-04T11:05:52.100Z",
        think: [],
        calls: [
          {
            id: "call_cal_1",
            name: "Bash",
            dig: "gcal agenda --date tomorrow --after 12:00",
            raw: '{\n  "command": "gcal agenda --date tomorrow --after 12:00"\n}',
            ok: true,
          },
        ],
        text: "Tomorrow afternoon you have a 1:1 with Paola at 14:00 and the dentist at 16:30.",
        u: { i: 4210, o: 320, c: 0, cost: 0.028 },
      },
      {
        k: "result",
        ts: "2026-07-04T11:05:55.400Z",
        tcid: "call_cal_1",
        tool: "Bash",
        ok: true,
        dig: "2 events",
        text: "14:00 1:1 Paola (30m)\n16:30 Dentist — Via Roma",
      },
    ],
  },

  // 4 — MEMORY, silent. A background memory-curation pass.
  {
    id: "f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8",
    cwd: "/Users/example/personal-agent",
    instance: "personal-agent",
    sourceId: "personal-agent",
    startTs: "2026-07-04T03:00:02.010Z",
    durMs: 96120,
    kind: "proactive",
    trigger: "cron",
    source: "memory",
    title: "Nightly memory curation",
    outcome: "silent",
    model: "gpt-5.5",
    provider: "openai-codex",
    api: "openai-codex-responses",
    effort: "low",
    instr:
      "Run the nightly memory-curation pass: consolidate the day's journal entries into the BuJo tiers, dedupe recalled facts, and prune stale reminders. Stay silent unless a consolidation error needs attention.",
    instrTr: false,
    hasRecall: true,
    recalled:
      "## Memory (recalled)\n\n- BuJo tiers: lite (rolling), journal (daily), bujo (curated).\n- Prune reminders older than 30 days unless pinned.\n- Embeddings via nomic-embed-text:v1.5.",
    recalledTr: false,
    finalText: "NOTHING_TO_REPORT",
    finalTr: false,
    status: "done",
    totals: {
      asst: 2,
      tcalls: 2,
      think: 1,
      tokIn: 12040,
      tokOut: 880,
      tokCache: 240000,
      cost: 0.071,
      steps: 5,
    },
    toolCounts: { memory_recall: 1, Edit: 1 },
    steps: [
      {
        k: "prompt",
        ts: "2026-07-04T03:00:02.210Z",
        text: "Run the nightly memory-curation pass. Stay silent unless a consolidation error needs attention.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T03:00:14.400Z",
        think: [
          {
            t: "Consolidating the day's journal into the BuJo tiers. I'll recall the current curated set, dedupe, then write back the consolidated entries.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_mem_1",
            name: "memory_recall",
            dig: "today's journal entries",
            raw: '{\n  "query": "today journal entries",\n  "k": 40\n}',
            ok: true,
          },
        ],
        text: "",
        u: { i: 8020, o: 410, c: 120000, cost: 0.041 },
      },
      {
        k: "result",
        ts: "2026-07-04T03:00:19.900Z",
        tcid: "call_mem_1",
        tool: "memory_recall",
        ok: true,
        dig: "17 entries recalled",
        text: "17 journal entries recalled; 3 near-duplicates flagged for merge.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T03:01:31.500Z",
        think: [],
        calls: [
          {
            id: "call_edit_1",
            name: "Edit",
            dig: "memory/bujo/2026-07-03.md",
            raw: '{\n  "file_path": "memory/bujo/2026-07-03.md",\n  "consolidated": 14\n}',
            ok: true,
          },
        ],
        text: "NOTHING_TO_REPORT",
        u: { i: 4020, o: 470, c: 120000, cost: 0.03 },
      },
      {
        k: "result",
        ts: "2026-07-04T03:01:38.130Z",
        tcid: "call_edit_1",
        tool: "Edit",
        ok: true,
        dig: "14 entries consolidated",
        text: "Wrote 14 consolidated entries; pruned 2 stale reminders.",
      },
    ],
  },

  // 5 — CRON briefing, notified, rich markdown final. The showcase card.
  {
    id: "a1b2c3d4e5f60718293a4b5c6d7e8f90",
    cwd: "/Users/example/personal-agent",
    instance: "personal-agent",
    sourceId: "personal-agent",
    startTs: "2026-07-04T06:30:00.400Z",
    durMs: 152300,
    kind: "briefing",
    trigger: "cron",
    source: "cron",
    title: "Morning briefing",
    outcome: "notified",
    model: "gpt-5.5",
    provider: "openai-codex",
    api: "openai-codex-responses",
    effort: "high",
    instr:
      "Compose the morning briefing: overnight email deltas worth knowing, today's calendar, the top 3 Todoist priorities, and one gentle nudge. Deliver it as the notification, verbatim.",
    instrTr: false,
    hasRecall: true,
    recalled:
      "## Memory (recalled)\n\n- Robert prefers the briefing under 120 words with a single nudge.\n- Focus block preference: 09:00–11:00.\n- Paola's schedule is shared read-only.",
    recalledTr: false,
    finalText:
      "### Morning briefing\n\n**Overnight:** nothing urgent — 2 newsletters filed, 0 action emails.\n\n**Today**\n1. 09:00 Focus block (held)\n2. 14:00 1:1 with Paola\n3. 16:30 Dentist\n\n**Top priorities**\n- Ship the `session-web` PWA\n- Review PR #117\n- Reply to the Maven thread\n\n*Nudge:* your 09:00 focus block is protected — start with the PWA before standup.",
    finalTr: false,
    status: "done",
    totals: {
      asst: 3,
      tcalls: 4,
      think: 3,
      tokIn: 41200,
      tokOut: 5210,
      tokCache: 410000,
      cost: 0.523,
      steps: 9,
    },
    toolCounts: { Bash: 3, read_skill: 1 },
    steps: [
      {
        k: "prompt",
        ts: "2026-07-04T06:30:00.700Z",
        text: "Compose the morning briefing and deliver it as the notification, verbatim.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T06:30:12.100Z",
        think: [
          {
            t: "I'll gather the three inputs in parallel: overnight mail deltas, today's calendar, and the top Todoist priorities. Then compose under 120 words with one nudge, per Robert's preference.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_b_mail",
            name: "Bash",
            dig: "gmail delta --since 12h",
            raw: '{\n  "command": "gmail delta --since 12h"\n}',
            ok: true,
          },
          {
            id: "call_b_cal",
            name: "Bash",
            dig: "gcal agenda --date today",
            raw: '{\n  "command": "gcal agenda --date today"\n}',
            ok: true,
          },
          {
            id: "call_b_td",
            name: "Bash",
            dig: "td list --filter 'today | p1'",
            raw: "{\n  \"command\": \"td list --filter 'today | p1'\"\n}",
            ok: true,
          },
        ],
        text: "",
        u: { i: 22100, o: 1210, c: 0, cost: 0.284 },
      },
      {
        k: "result",
        ts: "2026-07-04T06:30:18.400Z",
        tcid: "call_b_mail",
        tool: "Bash",
        ok: true,
        dig: "2 newsletters, 0 action",
        text: "filed: 2 newsletters · action-needed: 0",
      },
      {
        k: "result",
        ts: "2026-07-04T06:30:19.100Z",
        tcid: "call_b_cal",
        tool: "Bash",
        ok: true,
        dig: "3 events today",
        text: "09:00 Focus block\n14:00 1:1 Paola\n16:30 Dentist",
      },
      {
        k: "result",
        ts: "2026-07-04T06:30:20.050Z",
        tcid: "call_b_td",
        tool: "Bash",
        ok: true,
        dig: "3 priorities",
        text: "Ship session-web PWA\nReview PR #117\nReply to Maven thread",
      },
      {
        k: "assistant",
        ts: "2026-07-04T06:31:40.900Z",
        think: [
          {
            t: "Good, all three inputs are in. Let me double-check the focus-block preference in the briefing skill before I compose, so the nudge lands right.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_skill_b",
            name: "read_skill",
            dig: "briefing",
            raw: '{\n  "name": "briefing"\n}',
            ok: true,
          },
        ],
        text: "",
        u: { i: 9100, o: 640, c: 210000, cost: 0.121 },
      },
      {
        k: "result",
        ts: "2026-07-04T06:31:44.220Z",
        tcid: "call_skill_b",
        tool: "read_skill",
        ok: true,
        dig: "briefing skill: under 120 words, one nudge",
        text: "Keep the briefing under 120 words. Exactly one gentle nudge. Deliver verbatim via native notify.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T06:32:32.700Z",
        think: [
          {
            t: "Composing now — overnight, today, priorities, one nudge. Under 120 words.",
            tr: false,
          },
        ],
        calls: [],
        text: "### Morning briefing\n\n**Overnight:** nothing urgent — 2 newsletters filed, 0 action emails.\n\n**Today**\n1. 09:00 Focus block (held)\n2. 14:00 1:1 with Paola\n3. 16:30 Dentist",
        u: { i: 10000, o: 3360, c: 200000, cost: 0.118 },
      },
    ],
  },

  // 6 — CRON focus-scan, RUNNING (live). Partial run still streaming.
  {
    id: "c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4",
    cwd: "/Users/example/a8c-agents/orchestrator",
    instance: "orchestrator",
    sourceId: "orchestrator",
    startTs: "2026-07-04T12:00:00.900Z",
    durMs: 41200,
    kind: "focus-scan",
    trigger: "cron",
    source: "cron",
    title: "Midday orchestrator sweep",
    outcome: "notified",
    model: "claude-opus-4-8",
    provider: "anthropic",
    api: "anthropic-messages",
    effort: "medium",
    instr:
      "Run the midday sweep across the delegated task queues: check for blocked sub-agents, stale PRs awaiting review, and any failed runs since the morning sweep.",
    instrTr: false,
    hasRecall: false,
    finalText: "",
    finalTr: false,
    status: "running",
    totals: {
      asst: 1,
      tcalls: 2,
      think: 1,
      tokIn: 9800,
      tokOut: 410,
      tokCache: 0,
      cost: 0.118,
      steps: 3,
    },
    toolCounts: { Bash: 2 },
    steps: [
      {
        k: "prompt",
        ts: "2026-07-04T12:00:01.100Z",
        text: "Run the midday sweep across the delegated task queues.",
      },
      {
        k: "assistant",
        ts: "2026-07-04T12:00:12.700Z",
        think: [
          {
            t: "Starting the sweep — I'll check the blocked-task queue and stale PRs in parallel first, then triage anything that comes back.",
            tr: false,
          },
        ],
        calls: [
          {
            id: "call_run_1",
            name: "Bash",
            dig: "forge status --blocked",
            raw: '{\n  "command": "forge status --blocked"\n}',
            ok: true,
          },
          {
            id: "call_run_2",
            name: "Bash",
            dig: "gh pr list --search 'review:required updated:<-2d'",
            raw: "{\n  \"command\": \"gh pr list --search 'review:required updated:<-2d'\"\n}",
          },
        ],
        text: "",
        u: { i: 9800, o: 410, c: 0, cost: 0.118 },
      },
      {
        k: "result",
        ts: "2026-07-04T12:00:18.300Z",
        tcid: "call_run_1",
        tool: "Bash",
        ok: true,
        dig: "1 blocked task",
        text: "task#42 blocked: waiting on upstream lockfile",
      },
    ],
  },
];
