import { it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdir, writeFile, rm, symlink, copyFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// The exact P2b integration base, not an expectation generated by new code.
const BASE = "10f501d4f1dc102db9951fcebb09a96001910452";
it("is byte-identical to P2b for default journals/checkpoints/imports/ancestry/context and real provider payloads", async () => {
  const root = fileURLToPath(new URL("../../../../", import.meta.url));
  const baseline = join(root, "node_modules", `.p3a-parity-base-${process.pid}`);
  const source = "packages/harness/src/";
  try {
    const files = execFileSync("git", ["ls-tree", "-r", "--name-only", BASE, source], { cwd: root, encoding: "utf8" }).trim().split("\n").filter((p) => p.endsWith(".js") && !p.includes("/__tests__/"));
    for (const file of files) {
      const path = join(baseline, file.slice(source.length)); await mkdir(dirname(path), { recursive: true });
      await writeFile(path, execFileSync("git", ["show", `${BASE}:${file}`], { cwd: root }));
    }
    await symlink(join(root, "packages/harness/node_modules"), join(baseline, "node_modules"), "dir");
    await writeFile(join(baseline, "package.json"), '{"type":"module"}');
    const worker = fileURLToPath(new URL("./fixtures/projection-parity-worker.mjs", import.meta.url));
    const legacy = fileURLToPath(new URL("./fixtures/legacy-v4.jsonl", import.meta.url));
    const storage = join(root, "node_modules", `.p3a-parity-storage-${process.pid}`);
    await mkdir(`${storage}-import/legacy`, { recursive: true, mode: 0o700 });
    await copyFile(legacy, `${storage}-import/legacy/fixture_fixture-session.jsonl`);
    const capture = (src) => JSON.parse(execFileSync(process.execPath, ["--no-warnings", worker, src, storage, legacy], { cwd: root, encoding: "utf8", timeout: 30000 }));
    const before = capture(baseline); const after = capture(join(root, source));
    expect(after.wirePayloads).toHaveLength(2);
    for (const key of Object.keys(before)) expect(after[key], key).toEqual(before[key]);
    await rm(`${storage}-import`, { recursive: true, force: true });
    expect(after.bytes).not.toContain('"schemaVersion":3');
  } finally { await rm(baseline, { recursive: true, force: true }); }
}, 60000);
