export const PACKAGE_CATEGORIES = [
  "runtime",
  "core",
  "context",
  "execution",
  "observability",
  "evaluation",
  "communication",
  "operator-surface",
];

export const packageCatalog = [
  {
    dir: "a2a-adapter",
    name: "@worklab-ai/a2a-adapter",
    category: "communication",
    responsibility: "Exposes Mono Agent responders over A2A and consumes remote A2A agents through direct discovery.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "agent-contracts",
    name: "@worklab-ai/agent-contracts",
    category: "core",
    responsibility: "Defines shared structural request, response, stream, responder, and cancellation contracts.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "agent-evals",
    name: "@worklab-ai/agent-evals",
    category: "evaluation",
    responsibility: "Runs local-first end-to-end eval scenarios against Mono Agent responders and harnesses.",
    allowedDependencyCategories: ["core", "execution", "observability", "evaluation"],
    publishable: true,
  },
  {
    dir: "agent-harness",
    name: "@worklab-ai/agent-harness",
    category: "execution",
    responsibility: "Composes context, runtime, memory, history, tool policy, skills, and observability for one request.",
    allowedDependencyCategories: ["core", "context", "runtime", "observability"],
    publishable: true,
  },
  {
    dir: "agent-host",
    name: "@worklab-ai/agent-host",
    category: "execution",
    responsibility: "Builds configured Mono Agent harnesses and responders from adapter-neutral host config.",
    allowedDependencyCategories: ["core", "context", "runtime", "observability", "execution"],
    publishable: true,
  },
  {
    dir: "agent-orchestrator",
    name: "@worklab-ai/agent-orchestrator",
    category: "execution",
    responsibility: "Exposes named collaborator responders to an orchestrator runtime through a bounded MCP tool.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "claude-agents-runtime",
    name: "@worklab-ai/claude-agents-runtime",
    category: "runtime",
    responsibility: "Adapts @anthropic-ai/claude-agent-sdk to the Mono Agent runtime contract.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "codex-app-runtime",
    name: "@worklab-ai/codex-app-runtime",
    category: "runtime",
    responsibility: "Adapts the OpenAI Codex app-server CLI to the Mono Agent runtime contract.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "config",
    name: "@worklab-ai/config",
    category: "core",
    responsibility: "Loads adapter-neutral runtime, context, memory, tool, and artifact settings.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "cron-adapter",
    name: "@worklab-ai/cron-adapter",
    category: "communication",
    responsibility: "Invokes Mono Agent responders from cron schedules with skip-overlap execution.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "context",
    name: "@worklab-ai/context",
    category: "context",
    responsibility: "Builds deterministic prompt context from identity, soul, skills, history, and user messages.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "memory-md",
    name: "@worklab-ai/memory-md",
    category: "context",
    responsibility: "Provides optional Markdown memory storage for host-owned summaries.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "memory-journal",
    name: "@worklab-ai/memory-journal",
    category: "context",
    responsibility: "Provides a global daily-journal memory store: continuous journaling and an always-in-context today note.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "memory-graph",
    name: "@worklab-ai/memory-graph",
    category: "context",
    responsibility: "Provides a local JSONL entity/relation/observation knowledge graph for long-term memory.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "memory-search",
    name: "@worklab-ai/memory-search",
    category: "context",
    responsibility: "Provides local semantic search via embeddings and a brute-force cosine vector index over memory.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "memory-mcp",
    name: "@worklab-ai/memory-mcp",
    category: "context",
    responsibility: "Exposes journaling, entity-graph, and keyword/semantic-search memory tools to runtimes over an MCP stdio server.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "openai-agents-runtime",
    name: "@worklab-ai/openai-agents-runtime",
    category: "runtime",
    responsibility: "Adapts @openai/agents to the Mono Agent runtime contract.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "observability",
    name: "@worklab-ai/observability",
    category: "observability",
    responsibility: "Records and reads local JSONL run artifacts, summaries, and trace source manifests.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "openai-api-adapter",
    name: "@worklab-ai/openai-api-adapter",
    category: "communication",
    responsibility: "Exposes Mono Agent responders through OpenAI-compatible model discovery and Chat Completions endpoints.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "operator-console",
    name: "@worklab-ai/operator-console",
    category: "operator-surface",
    responsibility: "Serves the local browser settings and traceability operator surface.",
    allowedDependencyCategories: ["core", "observability"],
    publishable: true,
  },
  {
    dir: "runtime-adapter",
    name: "@worklab-ai/runtime-adapter",
    category: "runtime",
    responsibility: "Wraps @worklab-ai/agent-runtime behind Mono Agent runtime contracts.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "settings",
    name: "@worklab-ai/settings",
    category: "core",
    responsibility: "Defines generic field groups, patch validation, redaction, and JSON settings storage.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "skills",
    name: "@worklab-ai/skills",
    category: "context",
    responsibility: "Loads explicitly selected skills and turns them into context blocks.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "slack-adapter",
    name: "@worklab-ai/slack-adapter",
    category: "communication",
    responsibility: "Adapts Slack Socket Mode events to structural agent requests and streamed replies.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "telegram-adapter",
    name: "@worklab-ai/telegram-adapter",
    category: "communication",
    responsibility: "Adapts Telegram updates to structural agent requests and streamed replies.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "tool-policy",
    name: "@worklab-ai/tool-policy",
    category: "core",
    responsibility: "Normalizes fail-closed tool and MCP policy into runtime options.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "tui",
    name: "@worklab-ai/tui",
    category: "operator-surface",
    responsibility: "Provides an Ink terminal chat and read-only config operator surface.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "whatsapp-adapter",
    name: "@worklab-ai/whatsapp-adapter",
    category: "communication",
    responsibility: "Adapts WhatsApp messages to structural agent requests and streamed replies.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "webhook-adapter",
    name: "@worklab-ai/webhook-adapter",
    category: "communication",
    responsibility: "Invokes Mono Agent responders from HTTP webhook requests with sync and async modes.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
];

export function packageByName() {
  return new Map(packageCatalog.map((entry) => [entry.name, entry]));
}

export function packageByDir() {
  return new Map(packageCatalog.map((entry) => [entry.dir, entry]));
}
