export const PACKAGE_CATEGORIES = [
  "runtime",
  "core",
  "context",
  "execution",
  "observability",
  "evaluation",
  "communication",
  "operator-surface",
  "app",
];

export const packageCatalog = [
  {
    dir: "a2a-adapter",
    name: "@mono-agent/a2a-adapter",
    category: "communication",
    responsibility: "Exposes agent responders over A2A and consumes remote A2A agents through direct discovery.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "agent-app",
    name: "@mono-agent/agent-app",
    category: "app",
    responsibility: "Runs a config-first agent host: loads mono-agent.config.json, builds the responder, and starts every configured channel, operator console, and traceability.",
    allowedDependencyCategories: [
      "core",
      "context",
      "runtime",
      "execution",
      "observability",
      "communication",
      "operator-surface",
    ],
    publishable: true,
  },
  {
    dir: "agent-contracts",
    name: "@mono-agent/agent-contracts",
    category: "core",
    responsibility: "Defines shared structural request, response, stream, responder, and cancellation contracts.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "agent-evals",
    name: "@mono-agent/agent-evals",
    category: "evaluation",
    responsibility: "Runs local-first end-to-end eval scenarios against agent responders and harnesses.",
    allowedDependencyCategories: ["core", "execution", "observability", "evaluation"],
    publishable: true,
  },
  {
    dir: "agent-harness",
    name: "@mono-agent/agent-harness",
    category: "execution",
    responsibility: "Composes context, runtime, memory, history, tool policy, skills, and observability for one request.",
    allowedDependencyCategories: ["core", "context", "runtime", "observability"],
    publishable: true,
  },
  {
    dir: "agent-host",
    name: "@mono-agent/agent-host",
    category: "execution",
    responsibility: "Builds configured agent harnesses and responders from adapter-neutral host config.",
    allowedDependencyCategories: ["core", "context", "runtime", "observability", "execution"],
    publishable: true,
  },
  {
    dir: "agent-orchestrator",
    name: "@mono-agent/agent-orchestrator",
    category: "execution",
    responsibility: "Exposes named collaborator responders to an orchestrator runtime through a bounded MCP tool.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "agent-runtime",
    name: "@mono-agent/agent-runtime",
    category: "runtime",
    responsibility: "Provides the multi-backend agent runtime bridges (Claude SDK, Claude Code CLI, Codex app-server, Pi SDK) with provider session support.",
    allowedDependencyCategories: ["runtime"],
    publishable: true,
  },
  {
    dir: "config",
    name: "@mono-agent/config",
    category: "core",
    responsibility: "Loads adapter-neutral runtime, context, memory, tool, and artifact settings.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "cron-adapter",
    name: "@mono-agent/cron-adapter",
    category: "communication",
    responsibility: "Invokes agent responders from cron schedules with skip-overlap execution.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "context",
    name: "@mono-agent/context",
    category: "context",
    responsibility: "Builds deterministic prompt context from identity, soul, skills, history, and user messages.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "memory-md",
    name: "@mono-agent/memory-md",
    category: "context",
    responsibility: "Provides optional Markdown memory storage for host-owned summaries.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "memory-journal",
    name: "@mono-agent/memory-journal",
    category: "context",
    responsibility: "Provides a global daily-journal memory store: continuous journaling and an always-in-context today note.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "memory-graph",
    name: "@mono-agent/memory-graph",
    category: "context",
    responsibility: "Provides a local JSONL entity/relation/observation knowledge graph for long-term memory.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "memory-search",
    name: "@mono-agent/memory-search",
    category: "context",
    responsibility: "Provides local semantic search via embeddings and a brute-force cosine vector index over memory.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "memory-mcp",
    name: "@mono-agent/memory-mcp",
    category: "context",
    responsibility: "Exposes journaling, entity-graph, and keyword/semantic-search memory tools to runtimes over an MCP stdio server.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "openai-agents-runtime",
    name: "@mono-agent/openai-agents-runtime",
    category: "runtime",
    responsibility: "Adapts @openai/agents to the runtime contract.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "observability",
    name: "@mono-agent/observability",
    category: "observability",
    responsibility: "Records and reads local JSONL run artifacts, summaries, and trace source manifests.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "openai-api-adapter",
    name: "@mono-agent/openai-api-adapter",
    category: "communication",
    responsibility: "Exposes agent responders through OpenAI-compatible model discovery and Chat Completions endpoints.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "operator-console",
    name: "@mono-agent/operator-console",
    category: "operator-surface",
    responsibility: "Serves the local browser settings and traceability operator surface.",
    allowedDependencyCategories: ["core", "observability"],
    publishable: true,
  },
  {
    dir: "runtime-adapter",
    name: "@mono-agent/runtime-adapter",
    category: "runtime",
    responsibility: "Wraps @mono-agent/agent-runtime behind runtime contracts.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "sandbox",
    name: "@mono-agent/sandbox",
    category: "runtime",
    responsibility: "Normalizes fail-closed sandbox policy and prepares native sandboxed command execution.",
    allowedDependencyCategories: ["core", "runtime"],
    publishable: true,
  },
  {
    dir: "settings",
    name: "@mono-agent/settings",
    category: "core",
    responsibility: "Defines generic field groups, patch validation, redaction, and JSON settings storage.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "skills",
    name: "@mono-agent/skills",
    category: "context",
    responsibility: "Loads explicitly selected skills and turns them into context blocks.",
    allowedDependencyCategories: ["core", "context"],
    publishable: true,
  },
  {
    dir: "slack-adapter",
    name: "@mono-agent/slack-adapter",
    category: "communication",
    responsibility: "Adapts Slack Socket Mode events to structural agent requests and streamed replies.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "telegram-adapter",
    name: "@mono-agent/telegram-adapter",
    category: "communication",
    responsibility: "Adapts Telegram updates to structural agent requests and streamed replies.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "tool-policy",
    name: "@mono-agent/tool-policy",
    category: "core",
    responsibility: "Normalizes fail-closed tool and MCP policy into runtime options.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "tui",
    name: "@mono-agent/tui",
    category: "operator-surface",
    responsibility: "Provides an Ink terminal chat and read-only config operator surface.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "whatsapp-adapter",
    name: "@mono-agent/whatsapp-adapter",
    category: "communication",
    responsibility: "Adapts WhatsApp messages to structural agent requests and streamed replies.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
  {
    dir: "webhook-adapter",
    name: "@mono-agent/webhook-adapter",
    category: "communication",
    responsibility: "Invokes agent responders from HTTP webhook requests with sync and async modes.",
    allowedDependencyCategories: ["core"],
    publishable: true,
  },
];

export function packageByName() {
  return new Map(packageCatalog.map((entry) => [entry.name, entry]));
}

export function packageByDir() {
  return new Map(packageCatalog.map((entry) => [entry.dir, entry]));
}
